# -*- coding: utf-8 -*-
"""Classes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tfxBc8fge4XEFXqGkalHfZcVJINsKEWC
"""

class Dog():
    def __init__(self,name_1,age):
      #self.name is the attribute of name within the dog class
      #name is the parameter that i got in the init function
        self.name = name_1
        self.age = age
    def whats_your_name(self):
        print(self.name)

sally = Dog("Sally",1)
sally.whats_your_name()

spot = Dog("Spot",2)
spot.whats_your_name()

class Person():
  def __init__(self, name, age):
    self.name = name
    self.age = age
  #dunder = double underscore
  def __repr__(self):
    return f"this person's name is {self.name} and his age is {self.age}"
  # def __add__(self, other): # self+other
  #   return self.age + other.age


john = Person("John", 36)
peter = Person("Peter", 30)
print(john + peter)

class Point():
    def __init__(self, x, y):
        self.x = x
        self.y = y

## create an instance of the class
p = Point(3,4)

## access the attributes
print("p.x is:", p.x)
print("p.y is:", p.y)

class Dog():
    # Initializer / Instance Attributes
    def __init__(self, name_of_the_dog):
        print("A new dog has been initialized !")
        print("His name is", name_of_the_dog)
        self.name = name_of_the_dog

    def bark(self):
        print("{} barks ! WAF".format(self.name))

    def walk(self, number_of_meters):
        print("{} walked {} meters".format(self.name, number_of_meters))

shelter_dog = Dog("Rex")
shelter_dog.walk(10)

class Dog():
    # Initializer / Instance Attributes
    def __init__(self, name_of_the_dog):
        print("A new dog has been initialized !")
        print("His name is", name_of_the_dog)
        self.name = name_of_the_dog

    def bark(self):
        print("{} barks ! WAF".format(self.name))

    def walk(self, number_of_meters):
        print("{} walked {} meters".format(self.name, number_of_meters))

    def rename(self, new_name):
        self.name = new_name

shelter_dog = Dog("Rex")
shelter_dog.name = "Paul"

print(shelter_dog.name)

shelter_dog.walk(10)

class Computer():

    def description(self, name):
        """
        This is a totally useless function
        """
        print("I am a computer, my name is", name)
        #Analyse the line below
        print(self)
    def __repr__(self):
        return "This is a computer: {}".format(self.brand)

mac_computer = Computer()
mac_computer.brand = "Apple"
print(mac_computer.brand)

windows = Computer()
windows.brand = "Microsoft"
print(windows.brand)

dell_computer = Computer()
dell_computer.brand = "Windows"
Computer.description(dell_computer, "Mark")

# IS THE SAME AS:
dell_computer.description("Mark")

class Dog():

    # Initializer / Instance Attributes
    def __init__(self):
        print("A new dog has been initialized !")

shelter_dog = Dog()

sally = Dog()